CFLAGS += -ffreestanding -Wall -Wextra
CC = aarch64-none-elf-gcc

AR = aarch64-none-elf-ar

AFLAGS += -c
AS = aarch64-none-elf-as

LD := $(CC)
LDFLAGS = -nostdlib -ffreestanding

OBJCOPY = aarch64-none-elf-objcopy

QEMU = cp /usr/share/AAVMF/AAVMF_VARS.fd vars.fd && qemu-system-aarch64 \
  -machine virt \
  -cpu cortex-a57 \
  -m 1G \
  \
  -drive if=pflash,format=raw,readonly=on,file=/usr/share/AAVMF/AAVMF_CODE.fd \
  -drive if=pflash,format=raw,file=vars.fd \
  \
  -device virtio-scsi-pci,id=scsi0 \
  -drive if=none,file=os.img,format=raw,id=hd0 \
  -device scsi-hd,drive=hd0

EFI = yes
EFI_ARCH = arm64-efi
EFI_NAME = bootaa64.efi