CFLAGS += -ffreestanding -Wall -Wextra
CC = aarch64-none-elf-gcc

AR = aarch64-none-elf-ar

AFLAGS += -c
AS = aarch64-none-elf-as

LD := $(CC)
LDFLAGS = -nostdlib -ffreestanding

QEMU = qemu-system-aarch64 \
  -machine virt,acpi=on \
  -cpu cortex-a72 \
  -smp 2 \
  -m 4G \
  -bios /usr/share/AAVMF/AAVMF_CODE.fd \
  -drive if=pflash,format=raw,file=/usr/share/AAVMF/AAVMF_VARS.fd \
  -device qemu-xhci \
  -drive if=none,format=raw,file=usb.img,id=usbstick \
  -device usb-storage,drive=usbstick