CFLAGS += -mcmodel=medany -ffreestanding -Wall -Wextra
CC = riscv64-linux-gcc

AR = riscv64-linux-ar

AFLAGS += -c
AS = riscv64-linux-as

LD := $(CC)
LDFLAGS = -nostdlib -ffreestanding

QEMU = qemu-system-riscv64 -machine virt -bios default -nographic -kernel

